"""struttura modulare: tabelle utente e sessione

Revision ID: 212dab6f7df5
Revises: 
Create Date: 2026-10-01 13:27:34.541323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212dab6f7df5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('ruolo', sa.String(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.Column('creato_il', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utenti_email'), 'utenti', ['email'], unique=True)
    op.create_index(op.f('ix_utenti_id'), 'utenti', ['id'], unique=False)
    op.create_table('sessioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('scade_il', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessioni_id'), 'sessioni', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessioni_id'), table_name='sessioni')
    op.drop_table('sessioni')
    op.drop_index(op.f('ix_utenti_id'), table_name='utenti')
    op.drop_index(op.f('ix_utenti_email'), table_name='utenti')
    op.drop_table('utenti')
    # ### end Alembic commands ###
